// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsczMnfvRl_qUiyxvsNrXfvN_wKHfDUU4',
    appId: '1:663557892959:web:4593d440379c7a65e624ea',
    messagingSenderId: '663557892959',
    projectId: 'ecommerce-f0019',
    authDomain: 'ecommerce-f0019.firebaseapp.com',
    storageBucket: 'ecommerce-f0019.firebasestorage.app',
    measurementId: 'G-VF77QEYFYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYloEBu248ue-njF6Nm98VQ7WzxBhMJxo',
    appId: '1:663557892959:android:8072ef148b36d6eee624ea',
    messagingSenderId: '663557892959',
    projectId: 'ecommerce-f0019',
    storageBucket: 'ecommerce-f0019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRPIBRlCmOmrrHzZH_hnx7dzm0BnsBXc',
    appId: '1:663557892959:ios:64fbe6422da738b4e624ea',
    messagingSenderId: '663557892959',
    projectId: 'ecommerce-f0019',
    storageBucket: 'ecommerce-f0019.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDisplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyRPIBRlCmOmrrHzZH_hnx7dzm0BnsBXc',
    appId: '1:663557892959:ios:64fbe6422da738b4e624ea',
    messagingSenderId: '663557892959',
    projectId: 'ecommerce-f0019',
    storageBucket: 'ecommerce-f0019.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDisplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsczMnfvRl_qUiyxvsNrXfvN_wKHfDUU4',
    appId: '1:663557892959:web:67e1ccee3c9dcdc1e624ea',
    messagingSenderId: '663557892959',
    projectId: 'ecommerce-f0019',
    authDomain: 'ecommerce-f0019.firebaseapp.com',
    storageBucket: 'ecommerce-f0019.firebasestorage.app',
    measurementId: 'G-GNS1BT34RN',
  );
}
